env:
  dev

spring:
  cloud:
    stream:
      bindings:
        decr_product_count:
          destination: decr_product_count  #exchange名称，交换模式默认是topic
          group: product
        decr_product_count_result:
          destination: decr_product_count_result
          group: product
        incr_product_count:
          destination: incr_product_count
          group: product
        incr_product_count_result:
          destination: incr_product_count_result
          group: product
  datasource:
      name: product-service
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mmall?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
  rabbitmq:
    host: www.oecoo.com
    port: 5672
    username: guest
    password: guest
    
feign:
  client:
    config:
      feignName:
        connectTimeout: 20000
        readTimeout: 20000
