env:
  dev

spring:
  cloud:
#   Config2.x 版本使用webhooks无法刷新client配置的解决方案
    bus:
      id: ${spring.application.name}:${spring.cloud.config.profile}:${random.value}
  rabbitmq:
      host: www.oecoo.com
      port: 5672
      username: guest
      password: guest
      
management:
  endpoints:
    web:
      exposure:
        include: monitor

zuul:
#   重置全局敏感头 保证路由时携带必要的 request-header信息
  sensitive-headers:
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000
    max-total-connections: 20000
#   设置不对外 的 Api，让其仅在服务间调用可用，外部不可访问
  ignored-patterns:
    - /**/*Mapper/**
  routes:
#   /product/** -> /mmall-product-service/**  路由至对应服务下的 Api
#   1.0 标准写法
    product:
      path: /product/**
      serviceId: mmall-product-service
#      重置敏感头，保证路由时携带 request-header信息
#      sensitiveHeaders:
    cart:
      path: /cart/**
      serviceId: mmall-cart-service
    order:
      path: /order/**
      serviceId: mmall-order-service
    shipping:
      path: /shipping/**
      serviceId: mmall-shipping-service
    user:
      path: /user/**
      serviceId: mmall-user-service
#    config:
#      path: /config/**
#      serviceId: mmall-api-gateway-zuul
#   2.0 简洁写法
#      mmall-product-service: /product/**
#      mmall-cart-service: /cart/**
#      mmall-order-service: /order/**
#      mmall-shipping-service: /shipping/**
#      mmall-user-service: /user/**
