env:
  dev
  
user:
  name: greenwwasa
  age: 25
  
spring:
#  cloud:
#     Config2.x 版本使用webhooks无法刷新client配置的解决方案
#    bus:
#      id: ${spring.application.name}:${spring.cloud.config.profile}:${random.value}
  datasource:
    name: user-service
    url: jdbc:mysql://127.0.0.1:3306/mmall?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: www.oecoo.com
    port: 5672
    username: guest
    password: guest
    
#management:
#  endpoints:
#    web:
#      exposure:
#        include: monitor
